Repository codestates-seb/seb39_main_056, pull requests merged in 2022-10, with the labels that each got.

#30 Feature/nem 211 장바구니 도메인 구현
  server/src/docs/asciidoc/cart.adoc
  server/src/docs/asciidoc/cart.html
  server/src/main/generated/com/noterror/app/api/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/domain/cart/controller/CartController.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartDetailDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartPatchDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartProductDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/repository/CartDetailRepository.java
  server/src/main/java/com/noterror/app/api/domain/cart/repository/CartRepository.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartService.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/entity/Cart.java
  server/src/main/java/com/noterror/app/api/domain/entity/CartDetail.java
  server/src/main/java/com/noterror/app/api/domain/entity/Member.java
  server/src/main/java/com/noterror/app/api/domain/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/member/controller/MemberController.java
  server/src/main/java/com/noterror/app/api/domain/member/memberService/MemberService.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductService.java
  server/src/main/java/com/noterror/app/api/global/response/MultiCartResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleCartResponse.java
  server/src/main/resources/application.yml
  server/src/main/resources/db/h2/data.sql
  server/src/test/java/com/noterror/app/api/domain/product/controller/CartControllerTest.java
  server/src/test/java/com/noterror/app/restdocs/CartControllerRestDocs.java
  server/src/test/java/com/noterror/app/restdocs/ProductControllerRestDocs.java
Labels: Backend, feature, 장바구니

#32 NEM-212 / feat : 주문_도메인_구현
  server/src/main/generated/com/noterror/app/api/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/noterror/app/api/domain/orders/mapper/OrdersMapperImpl.java
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/domain/entity/Member.java
  server/src/main/java/com/noterror/app/api/domain/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/entity/order/Orders.java
  server/src/main/java/com/noterror/app/api/domain/entity/order/OrdersProduct.java
  server/src/main/java/com/noterror/app/api/domain/entity/order/OrdersStatus.java
  server/src/main/java/com/noterror/app/api/domain/orders/controller/OrdersController.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrdersProduct.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrdersProductResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrdersResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/repository/OrdersRepository.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersService.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersServiceImpl.java
  server/src/main/java/com/noterror/app/api/global/response/MultiOrdersResponse.java
Labels: Backend, feature, 주문

#35 Feature : 주문 조회 및 주문하기 기능
  server/src/main/generated/com/noterror/app/api/domain/orders/mapper/OrdersMapperImpl.java
  server/src/main/java/com/noterror/app/api/domain/entity/Member.java
  server/src/main/java/com/noterror/app/api/domain/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/entity/order/OrderProduct.java
  server/src/main/java/com/noterror/app/api/domain/entity/order/Orders.java
  server/src/main/java/com/noterror/app/api/domain/entity/order/OrdersProduct.java
  server/src/main/java/com/noterror/app/api/domain/orders/controller/OrdersController.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderInfoDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderProductDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrdersProduct.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrdersProductResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/repository/OrderProductRepository.java
  server/src/main/java/com/noterror/app/api/domain/orders/repository/OrdersRepository.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersService.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersServiceImpl.java
  server/src/main/java/com/noterror/app/api/global/exception/OutOfStockException.java
  server/src/main/java/com/noterror/app/api/global/response/MultiOrdersResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleOrderResponse.java
  server/src/main/resources/application.yml
Labels: Backend, feature

#34 Feature/NEM-213 카테고리 및 유형별 조회 기능 구현
  server/src/main/generated/com/noterror/app/api/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/admin/AdminProductController.java
  server/src/main/java/com/noterror/app/api/domain/category/README.md
  server/src/main/java/com/noterror/app/api/domain/category/controller/CategoryController.java
  server/src/main/java/com/noterror/app/api/domain/category/dto/CategoryResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/category/repository/CategoryRepository.java
  server/src/main/java/com/noterror/app/api/domain/category/service/CategoryService.java
  server/src/main/java/com/noterror/app/api/domain/category/service/CategoryServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/entity/Category.java
  server/src/main/java/com/noterror/app/api/domain/entity/VegeType.java
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/vegeType/controller/VegeTypeController.java
  server/src/main/java/com/noterror/app/api/domain/vegeType/dto/VegeTypeRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/vegeType/dto/VegeTypeResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/vegeType/repository/VegeTypeRepository.java
  server/src/main/java/com/noterror/app/api/domain/vegeType/service/VegeTypeService.java
  server/src/main/java/com/noterror/app/api/domain/vegeType/service/VegeTypeServiceImpl.java
  server/src/main/java/com/noterror/app/api/global/response/ListVegeTypeResponse.java
  server/src/main/java/com/noterror/app/api/global/response/MultiProductResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleCategoryResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleProductResponse.java
  server/src/main/resources/application.yml
  server/src/main/resources/db/h2/data.sql
  server/src/test/java/com/noterror/app/restdocs/CategoryControllerRestDocs.java
  server/src/test/java/com/noterror/app/stubData/CategoryStubData.java
Labels: Backend, feature, 제품

#39 Feature/nem 227 장바구니 썸네일 이미지 추가
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartDetailDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartProductDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/repository/CartDetailRepository.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartServiceImpl.java
  server/src/main/java/com/noterror/app/api/entity/Cart.java
  server/src/test/java/com/noterror/app/infra/JwtTokenizerTest.java
  server/src/test/java/com/noterror/app/restdocs/CartControllerRestDocs.java
Labels: Backend, feature

#40 Feature/ NEM-225 / feat : 주문 memberId 제외
  server/src/main/java/com/noterror/app/api/domain/orders/controller/OrdersController.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersService.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersServiceImpl.java
  server/src/main/java/com/noterror/app/infra/config/SecurityConfig.java
  server/src/test/java/com/noterror/app/infra/JwtTokenizerTest.java
  server/src/test/java/com/noterror/app/restdocs/OrdersControllerRestDocs.java
Labels: Backend, feature, 주문

#47 Feature/nem 229 리팩토링 및 오류 수정
  server/.gitignore
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/ServerApplication.java
  server/src/main/java/com/noterror/app/api/domain/cart/controller/CartController.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartDetailDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartPatchDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartProductDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/repository/CartDetailRepository.java
  server/src/main/java/com/noterror/app/api/domain/cart/repository/CartRepository.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/category/controller/CategoryController.java
  server/src/main/java/com/noterror/app/api/domain/category/service/CategoryService.java
  server/src/main/java/com/noterror/app/api/domain/member/controller/MemberController.java
  server/src/main/java/com/noterror/app/api/domain/member/dto/MemberIdResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/member/dto/SignUpDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/controller/OrdersController.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderInfoDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderProductDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/product/mapper/ProductMapper.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductService.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/entity/Product.java
  server/src/main/java/com/noterror/app/api/entity/cart/Cart.java
  server/src/main/java/com/noterror/app/api/entity/cart/CartDetail.java
  server/src/main/java/com/noterror/app/api/entity/member/Member.java
  server/src/main/java/com/noterror/app/api/entity/order/OrderProduct.java
  server/src/main/java/com/noterror/app/api/entity/order/Orders.java
  server/src/main/java/com/noterror/app/api/global/audit/Auditable.java
  server/src/main/java/com/noterror/app/api/global/audit/README.md
  server/src/main/java/com/noterror/app/api/global/response/ListVegetarianTypeResponse.java
  server/src/main/java/com/noterror/app/api/global/response/MultiCartResponse.java
  server/src/main/java/com/noterror/app/api/global/response/MultiOrdersResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleCartResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleCategoryResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleMemberResponse.java
  server/src/main/java/com/noterror/app/api/global/response/SingleOrderResponse.java
  server/src/main/java/com/noterror/app/infra/config/SecurityConfig.java
  server/src/main/resources/application-auth.yml
  server/src/main/resources/db/h2/data.sql
  server/src/test/java/com/noterror/app/api/domain/product/controller/FeatureTestOfAdminProductController.java
  server/src/test/java/com/noterror/app/api/domain/product/controller/GetSortedProductsTestOfProductController.java
  server/src/test/java/com/noterror/app/restdocs/OrdersControllerRestDocs.java
  server/src/test/java/com/noterror/app/stubData/ProductStubData.java
Labels: bug, Backend, feature, Refactoring

#44 Feature/nem 187 소셜 로그인 페이지
  client/.env
  client/package-lock.json
  client/src/App.css
  client/src/App.js
  client/src/actions/index.js
  client/src/assets/ariana.jpg
  client/src/assets/brian.png
  client/src/assets/chris.png
  client/src/assets/franz.jpg
  client/src/assets/paul.jpg
  client/src/assets/steven.png
  client/src/assets/toby.jpg
  client/src/assets/tolstoy.jpg
  client/src/assets/tyson.jpg
  client/src/components/atom/BodyContainer.js
  client/src/components/atom/MainColorBtn.js
  client/src/components/atom/StyledInput.js
  client/src/components/molecule/GoogleBtn.js
  client/src/components/organism/Address.js
  client/src/components/organism/InputContainer.js
  client/src/components/organism/TypeTable.js
  client/src/components/pages/Info.js
  client/src/components/pages/Login.js
  client/src/components/pages/Register.js
  client/src/components/pages/Signup.js
  client/src/components/pages/Type.js
  client/src/components/templates/CenterBox.js
  client/src/components/templates/Info/Info.js
  client/src/components/templates/Info/style.js
  client/src/components/templates/InfoBox.js
  client/src/components/templates/Login/Login.js
  client/src/components/templates/Login/Style.js
  client/src/components/templates/Type/Type.js
  client/src/components/templates/Type/style.js
  client/src/index.css
  client/src/reducers/index.js
Labels: feature, 인증, frontend, page, jwt

#45 Feature/nem 218 장바구니 페이지
  client/.gitignore
  client/package.json
  client/seongdata.json
  client/src/App.js
  client/src/actions/index.js
  client/src/components/organism/CartItem/CartItem.js
  client/src/components/organism/CartItem/Style.js
  client/src/components/organism/CartList.js
  client/src/components/organism/GoogleBtn.js
  client/src/components/organism/InputContainer.js
  client/src/components/organism/StyledInput.js
  client/src/components/pages/Cart.js
  client/src/components/pages/Info.js
  client/src/components/pages/Login.js
  client/src/components/pages/Register.js
  client/src/components/templates/Cart/Cart.js
  client/src/components/templates/Cart/Style.js
  client/src/components/templates/InfoBox.js
  client/src/components/templates/Type/Type.js
  client/src/reducers/cartReducer.js
  client/src/reducers/index.js
Labels: feature, frontend, 장바구니

#53 Feature/nem 187 소셜 로그인 페이지
  client/.gitignore
  client/src/App.js
  client/src/components/pages/Info.js
  client/src/components/templates/Login/Login.js
  client/src/components/templates/Type/Type.js
  client/src/service/setTokenHeader.js
Labels: bug, 인증, frontend, jwt

#55 Nem 234 장바구니수정 및 버그해결
  client/.env
  client/.gitignore
  client/src/App.js
  client/src/components/organism/FoodCard.js
  client/src/components/organism/FoodList.js
  client/src/components/organism/Header/index.js
  client/src/components/pages/Info.js
  client/src/components/pages/Mypage.js
  client/src/components/templates/Info/Info.js
  client/src/components/templates/Type/Type.js
  client/src/service/setTokenHeader.js
Labels: bug, feature, frontend

#59 Feature/nem 236 잠바구니내역 주문기능
  server/src/main/java/com/noterror/app/api/domain/cart/controller/CartController.java
  server/src/main/java/com/noterror/app/api/domain/cart/dto/CartOrderDto.java
  server/src/main/java/com/noterror/app/api/domain/cart/repository/CartDetailRepository.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartService.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersService.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersServiceImpl.java
  server/src/main/java/com/noterror/app/infra/config/AppConfig.java
  server/src/main/java/com/noterror/app/infra/config/SecurityConfig.java
  server/src/main/resources/application-auth.yml
Labels: Backend, feature, 장바구니

#61 NEM-230 / feat : 회원_유형별_제품_조회
  server/build.gradle
  server/src/docs/asciidoc/README.md
  server/src/docs/asciidoc/cart.adoc
  server/src/docs/asciidoc/product.adoc
  server/src/main/java/com/noterror/app/aop/LogAop.java
  server/src/main/java/com/noterror/app/aop/Readme.md
  server/src/main/java/com/noterror/app/api/domain/admin/AdminProductController.java
  server/src/main/java/com/noterror/app/api/domain/cart/controller/CartController.java
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/QueryParamDto.java
  server/src/main/java/com/noterror/app/api/domain/product/repository/ProductRepository.java
  server/src/main/java/com/noterror/app/api/domain/product/repository/ProductRepositoryCustom.java
  server/src/main/java/com/noterror/app/api/domain/product/repository/ProductRepositoryQueryDSL.java
  server/src/main/java/com/noterror/app/api/domain/product/repository/ProductRepositoryQueryDSLImpl.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductService.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/vegetarian/controller/VegeTypeController.java
  server/src/main/java/com/noterror/app/api/domain/vegetarian/dto/VegetarianTypeRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/vegetarian/dto/VegetarianTypeResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/vegetarian/repository/VegetarianTypeRepository.java
  server/src/main/java/com/noterror/app/api/domain/vegetarian/service/VegetarianTypeService.java
  server/src/main/java/com/noterror/app/api/domain/vegetarian/service/VegetarianTypeServiceImpl.java
  server/src/main/java/com/noterror/app/api/entity/Product.java
  server/src/main/java/com/noterror/app/api/entity/VegetarianType.java
  server/src/main/java/com/noterror/app/api/global/response/MultiCartsResponse.java
  server/src/main/java/com/noterror/app/api/global/response/MultiProductsResponse.java
  server/src/main/java/com/noterror/app/infra/config/AppConfig.java
  server/src/main/resources/db/h2/data.sql
  server/src/test/java/com/noterror/app/api/domain/product/controller/FeatureTestOfAdminProductController.java
  server/src/test/java/com/noterror/app/api/domain/product/controller/GetSortedProductsTestOfProductController.java
  server/src/test/java/com/noterror/app/api/domain/product/service/ProductServiceImplSliceTest.java
  server/src/test/java/com/noterror/app/stubData/CategoryStubData.java
  server/src/test/java/com/noterror/app/stubData/ProductStubData.java
Labels: Backend, feature, 제품, 인증, 핵심기능

#62 NEM-244 / feat : 초기 데이터 추가
  server/src/main/resources/db/h2/data.sql
Labels: Backend, 제품

#24 NEM-75 / docs : README 파일 수정
  README.md
Labels: documentation

#69 NEM-248 / feat : 서버운영환경설정
  server/src/main/java/com/noterror/app/api/domain/admin/AdminProductController.java
  server/src/main/java/com/noterror/app/api/domain/cart/controller/CartController.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartService.java
  server/src/main/java/com/noterror/app/api/domain/cart/service/CartServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/orders/controller/OrdersController.java
  server/src/main/java/com/noterror/app/api/domain/orders/dto/OrderDto.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersService.java
  server/src/main/java/com/noterror/app/api/domain/orders/service/OrdersServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/entity/Vegetarian.java
  server/src/main/java/com/noterror/app/api/entity/cart/CartDetail.java
  server/src/main/java/com/noterror/app/api/entity/order/Orders.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/main/resources/db/mysql/data.sql
  server/src/main/resources/db/mysql/schema.sql
Labels: Backend

#73 hotfix/refact_and_test_v.1.2.0
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/entity/Category.java
  server/src/main/java/com/noterror/app/api/entity/Product.java
  server/src/main/java/com/noterror/app/api/entity/member/Member.java
  server/src/main/java/com/noterror/app/api/global/exception/OutOfStockException.java
  server/src/main/java/com/noterror/app/infra/auth/MemberDetailsService.java
  server/src/main/java/com/noterror/app/infra/filter/JwtVerificationFilter.java
  server/src/main/java/com/noterror/app/infra/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/noterror/app/infra/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/noterror/app/infra/jwt/JwtTokenizer.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/db/h2/data.sql
  server/src/main/resources/db/mysql/cart/cart_schema.sql
  server/src/main/resources/db/mysql/cart_detail/cart_detail_schema.sql
  server/src/main/resources/db/mysql/constraint.sql
  server/src/main/resources/db/mysql/order/order_schema.sql
  server/src/main/resources/db/mysql/order_product/order_product_schema.sql
  server/src/main/resources/db/mysql/vegetarian/vegetarian_schema.sql
Labels: bug, Backend, MAIN, hotfix

#74 Hotfix/refact and test v.1.2.0
  server/src/main/java/com/noterror/app/infra/handler/MemberAccessDeniedHandler.java
  server/src/main/resources/application-server.yml
Labels: Backend, deploy, MAIN, hotfix, v.1.2.0

#68 docs : Readme 파일 수정
  README.md
Labels: documentation
