Repository codestates-seb/seb39_main_056, pull requests merged in 2022-09, with the labels that each got.

#17 Feature/nem 167 제품 수정 기능
  server/build.gradle
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/domain/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductPatchDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/product/mapper/ProductMapper.java
  server/src/main/java/com/noterror/app/api/domain/product/repository/ProductRepository.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductService.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/global/response/SingleProductResponse.java
  server/src/test/java/com/noterror/app/api/domain/product/controller/ProductControllerRestDocs.java
Labels: good first issue, Backend, feature, 제품

#20 NEM-166 / feat: 제품 등록+삭제 기능
  server/build.gradle
  server/src/docs/asciidoc/product.adoc
  server/src/main/java/com/noterror/app/api/domain/product/README.md
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/product/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/product/repository/ProductRepository.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductService.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/global/response/SingleProductResponse.java
  server/src/test/java/com/noterror/app/restdocs/ProductControllerRestDocs.java
Labels: Backend, feature, 제품

#26 Feature/nem 191 소셜 로그인 페이지
  client/.env
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/actions/index.js
  client/src/components/organism/.gitkeep
  client/src/components/organism/Address.js
  client/src/components/organism/GoogleBtn.js
  client/src/components/organism/InputContainer.js
  client/src/components/organism/PopupPostCode.js
  client/src/components/organism/Popupdom.js
  client/src/components/organism/StyledInput.js
  client/src/components/organism/TypeTable.js
  client/src/components/pages/.gitkeep
  client/src/components/pages/Info.js
  client/src/components/pages/Login.js
  client/src/components/pages/Register.js
  client/src/components/pages/Type.js
  client/src/components/templates/.gitkeep
  client/src/components/templates/InfoBox.js
  client/src/hooks/.gitkeep
  client/src/hooks/postLoginToken.js
  client/src/hooks/useScript.js
  client/src/index.js
  client/src/reducers/index.js
  client/src/reducers/loginReducer.js
  client/src/reducers/vegeTypeReducer.js
  client/src/store/.gitkeep
  client/src/store/store.js
  client/src/style/GlobalStyles.js
Labels: good first issue, feature, 인증, 소셜, frontend, page, 컴포넌트

#15 Feature/nem 194 header 컴포넌트 구현
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/assets/.gitkeep
  client/src/assets/aa.jpg
  client/src/assets/logo.jpg
  client/src/components/organism/Header.js
  client/src/style/.gitkeep
  client/src/style/GlobalStyles.js
Labels: feature, frontend, 컴포넌트, Header

#27 Feature/nem 199 예외처리로직 및 테스트
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/domain/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductPatchDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductPostDto.java
  server/src/main/java/com/noterror/app/api/domain/user/controller/MemberController.java
  server/src/main/java/com/noterror/app/api/domain/user/dto/MemberRequestDto.java
  server/src/main/java/com/noterror/app/api/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/noterror/app/api/global/exception/BusinessLogicException.java
  server/src/main/java/com/noterror/app/api/global/exception/ExceptionCode.java
  server/src/main/java/com/noterror/app/api/global/exception/response/ConstraintError.java
  server/src/main/java/com/noterror/app/api/global/exception/response/ErrorResponse.java
  server/src/main/java/com/noterror/app/api/global/exception/response/ValidationError.java
Labels: Backend, feature

#28 Feature/nem 198 기능별 테스트 코드 작성 및 리팩토링
  server/src/docs/asciidoc/product.adoc
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/admin/AdminProductController.java
  server/src/main/java/com/noterror/app/api/domain/entity/Member.java
  server/src/main/java/com/noterror/app/api/domain/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/entity/Role.java
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductPostDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/product/dto/ProductResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/product/mapper/ProductMapper.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductService.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/user/controller/MemberController.java
  server/src/main/java/com/noterror/app/api/domain/user/dto/MemberRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/user/dto/MemberResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/user/dto/SingleMemberResponse.java
  server/src/main/java/com/noterror/app/api/domain/user/repository/MemberRepository.java
  server/src/main/java/com/noterror/app/api/domain/user/userService/MemberService.java
  server/src/main/java/com/noterror/app/api/domain/user/userService/MemberServiceImpl.java
  server/src/main/java/com/noterror/app/infra/README.md
  server/src/main/resources/static/docs/product.html
  server/src/test/java/com/noterror/app/api/domain/product/controller/FeatureTestOfAdminProductController.java
  server/src/test/java/com/noterror/app/api/domain/product/controller/GetSortedProductsTestOfProductController.java
  server/src/test/java/com/noterror/app/api/domain/product/service/ProductServiceImplSliceTest.java
  server/src/test/java/com/noterror/app/restdocs/AdminProductControllerRestDocs.java
  server/src/test/java/com/noterror/app/restdocs/MemberControllerRestDocs.java
  server/src/test/java/com/noterror/app/restdocs/ProductControllerRestDocs.java
  server/src/test/java/com/noterror/app/stubData/ProductStubData.java
Labels: Backend, feature, Refactoring

#29 NEM-141 / feat : 유저 개인 정보 수정+조회 기능
  server/src/main/generated/com/noterror/app/api/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/noterror/app/api/domain/product/mapper/ProductMapperImpl.java
  server/src/main/java/com/noterror/app/api/domain/entity/Member.java
  server/src/main/java/com/noterror/app/api/domain/entity/Product.java
  server/src/main/java/com/noterror/app/api/domain/member/README.md
  server/src/main/java/com/noterror/app/api/domain/member/controller/MemberController.java
  server/src/main/java/com/noterror/app/api/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/noterror/app/api/domain/member/dto/MemberRequestDto.java
  server/src/main/java/com/noterror/app/api/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/noterror/app/api/domain/member/repository/MemberRepository.java
  server/src/main/java/com/noterror/app/api/domain/member/userService/MemberService.java
  server/src/main/java/com/noterror/app/api/domain/member/userService/MemberServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/product/controller/ProductController.java
  server/src/main/java/com/noterror/app/api/domain/product/mapper/ProductMapper.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductService.java
  server/src/main/java/com/noterror/app/api/domain/product/service/ProductServiceImpl.java
  server/src/main/java/com/noterror/app/api/domain/user/controller/MemberController.java
  server/src/main/java/com/noterror/app/api/domain/user/dto/MemberRegistrationResponseDto.java
  server/src/main/java/com/noterror/app/api/domain/user/userService/MemberService.java
  server/src/main/java/com/noterror/app/api/domain/user/userService/MemberServiceImpl.java
  server/src/main/java/com/noterror/app/api/global/response/SingleMemberResponse.java
  server/src/test/java/com/noterror/app/restdocs/MemberControllerRestDocs.java
  server/src/test/java/com/noterror/app/restdocs/ProductControllerRestDocs.java
Labels: Backend, feature

#16 Feature/nem 188 제품 상세 페이지
  client/.env
  client/src/components/pages/ProductPage.js
Labels: 제품, frontend, page
